---
development:
  cloud_name: kaoxyooj
  api_key: <%= ENV["CLOUDINARY_API"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: kaoxyooj
  api_key: <%= ENV["CLOUDINARY_API"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV["CLOUDINARY_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
