---
development:
  cloud_name: kaoxyooj
  api_key: '318337662641147'
  api_secret: oimZ-Mv1OtnZefqObzP4j2cmEt4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: kaoxyooj
  api_key: '318337662641147'
  api_secret: oimZ-Mv1OtnZefqObzP4j2cmEt4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: kaoxyooj
  api_key: '318337662641147'
  api_secret: oimZ-Mv1OtnZefqObzP4j2cmEt4
  enhance_image_tag: true
  static_image_support: false
